name: RFPilot
author: Sebastian Zwierzchowski <sebastian.zwierzchowski@gmail.com>
description: rf pilot phone version

environment:
  sdk: ">=1.19.0"

dependencies:
  browser: ^0.10.0+2
  service_worker:
